version: '3'

services:
  web:
    restart: always
    build: .
    volumes:
      - .:/code
    ports:
      - "8001:8000"
      - "5550:5555"
    links:
      - redis
      - db
    depends_on:
      - redis
      - db

  redis:
    image: redis:4.0-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  db:
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=podigger_ng
      - TZ=GMT-3
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
