# Generated by Django 2.1.3 on 2018-11-09 12:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nome')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, size=None)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'icone',
                'verbose_name_plural': 'icones',
                'db_table': 'icons',
            },
        ),
        migrations.CreateModel(
            name='IconFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_extension', models.CharField(choices=[('AI', 'ai'), ('EPS', 'eps'), ('JPG', 'jpg'), ('PDF', 'pdf'), ('PNG', 'png'), ('SVG', 'svg')], default='SVG', max_length=4, verbose_name='Formato')),
                ('icon_file', models.FileField(upload_to='icons/', verbose_name='Arquivo')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='icon_manager.Icon')),
            ],
            options={
                'verbose_name': 'arquivo',
                'verbose_name_plural': 'arquivos',
                'db_table': 'files',
            },
        ),
    ]
